quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes_app.urls")),
    path("users/", include("users.urls")),
]

quotes/quotes_app/urls.py
from django.urls import path

from . import views

app_name = "quotes_app"

urlpatterns = [
    path("", views.root, name="root"),
    path("<int:page>", views.root, name="root_paginate"),
    path("author-info/<str:author_id>/", views.author_info, name="author_info"),
    path("author-add/", views.author_add, name="author_add"),
    path("quote_add/", views.quote_add, name="quote_add"),
    path("quote-by-tag/<str:tag_id>/", views.quote_by_tag, name="quote_by_tag"),
    path("top-tags/", views.top_tags, name="top_tags"),
]

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views
from .forms import SigninForm

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path(
        "signin/",
        views.signinuser,
        name="signin",
    ),
    path(
        "signout/",
        LogoutView.as_view(template_name="users/signout.html"),
        name="signout",
    ),
    path("reset-password/", views.ResetPasswordView.as_view(), name="reset-password"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="reset-password-done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/quotes_app/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def get_quote_count(self):
        return self.quote_set.count()


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

quotes/quotes_app/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, Textarea

from .models import Author, Quote


class AuthorAddForm(ModelForm):
    fullname = CharField(
        max_length=50,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    born_date = CharField(
        max_length=50,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    born_location = CharField(
        max_length=150,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    description = CharField(
        required=True, widget=Textarea(attrs={"class": "form-control"})
    )

    class Meta:
        model = Author
        fields = (
            "fullname",
            "born_date",
            "born_location",
            "description",
        )


class AuthorChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.fullname


class QuoteAddForm(ModelForm):
    quote = CharField(
        required=True,
        widget=Textarea(attrs={"class": "form-control"}),
    )
    author = AuthorChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Quote
        fields = (
            "quote",
            "author",
        )

quotes/quotes_app/views.py
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AuthorAddForm, QuoteAddForm
from .models import Quote, Tag, Author


def root(request, page=1):
    quotes = Quote.objects.all().order_by("-created_at")
    quotes_list = []

    for quote in quotes:
        tags = quote.tags.all()
        quote_dict = {
            "quote": quote.quote,
            "tags": tags,
            "author": quote.author,
            "created_at": quote.created_at,
        }
        quotes_list.append(quote_dict)

    per_page = 10
    paginator = Paginator(list(quotes_list), per_page)
    quotes_on_page = paginator.page(page)

    return render(
        request,
        "quotes_app/index.html",
        context={
            "quotes": quotes_on_page,
        },
    )


def author_info(request, author_id):
    author = Author.objects.get(id=author_id)
    print(author.fullname)

    return render(request, "quotes_app/author_info.html", {"author": author})


@login_required
def author_add(request):
    form = AuthorAddForm(instance=Author())

    if request.method == "POST":
        form = AuthorAddForm(request.POST, instance=Author())
        if form.is_valid():
            author_name = form.cleaned_data["fullname"]

            author_exist = Author.objects.filter(fullname=author_name)

            if not author_exist:
                form.save()
                return redirect(to="/")

            messages.warning(
                request,
                message=f"Author {author_name} is already in database.",
            )
            return redirect(to="quotes_app:author_add")

    return render(request, "quotes_app/author_add.html", context={"form": form})


@login_required
def quote_add(request):
    form = QuoteAddForm(instance=Quote())

    if request.method == "POST":
        form = QuoteAddForm(request.POST, instance=Quote())

        if form.is_valid():
            form.save()

            messages.success(
                request,
                message=f"Quote has been added to database.",
            )
            return redirect(to="/")

    return render(request, "quotes_app/quote_add.html", context={"form": form})


def quote_by_tag(request, tag_id):
    print(tag_id)

    tag = get_object_or_404(Tag, id=tag_id)
    quotes = Quote.objects.filter(tags=tag)

    return render(request, "quotes_app/quotes_tag.html", {"tag": tag, "quotes": quotes})


def top_tags(request):
    top_tags = Tag.objects.annotate(num_quotes=Count("quote")).order_by("-num_quotes")[
        :10
    ]
    return render(request, "quotes_app/top-tags.html", {"top_tags": top_tags})

quotes/quotes_app/templates/quotes_app/author_add.html
{% extends 'quotes_app/base.html' %} {% block content %}
<div class="container mt-3 position-relative">
    <h2 class="mb-5">Add Author</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label add-author-form"
                >Author fullname {{ form.fullname }}
            </label>
            <div class="error-container">{{form.errors.fullname}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label add-author-form"
                >Born date {{ form.born_date }}
            </label>
            <div class="error-container">{{form.errors.born_date}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label add-author-form"
                >Born location {{ form.born_location }}
            </label>
            <div class="error-container">{{form.errors.born_location}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label add-author-form"
                >Author description {{ form.description }}
            </label>
            <div class="error-container">{{form.errors.description}}</div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>
    </form>
</div>
{% endblock %}

quotes/quotes_app/templates/quotes_app/author_info.html
{% extends 'quotes_app/base.html' %} {% block content %}

<div class="card shadow">
    <div class="card-body">
        <h5 class="card-title fs-1 mb-4">{{author.fullname}}</h5>
        <p class="card-text">
            <span class="fw-semibold">Born: </span
            ><span>{{author.born_date}}</span>
            <span>{{author.born_location}}</span>
        </p>
        <p class="card-text">
            <span class="fw-semibold">Description: </span>
            {{author.description}}
        </p>
    </div>
</div>
{% endblock %}

quotes/quotes_app/templates/quotes_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
        />
        {% load static %}
        <link rel="stylesheet" href="{% static 'quotes_app/styles.css'%}" />
        <title>Quotes app</title>
    </head>
    <body>
        <div class="container position-relative">
            <nav class="navbar">
                <a href="{% url 'quotes_app:root' %}" class="main-logo"
                    >Quotes to Scrape</a
                >

                <div class="container-fluid justify-content-end gap-4">
                    {% if user.is_authenticated %}

                    <span class="fs-4"
                        >Welcome,
                        <span class="fw-bold fst-italic"
                            >{{user.username}}</span
                        ></span
                    >

                    <form method="post" action="{% url 'users:signout' %}">
                        {% csrf_token %}
                        <button
                            class="btn btn-outline-primary me-2"
                            type="submit"
                        >
                            Sign out
                        </button>
                    </form>
                    {% else %}
                    <form class="container-fluid justify-content-end">
                        <a
                            class="btn btn-outline-primary me-2"
                            href="{% url 'users:signup' %}"
                        >
                            Sign up
                        </a>
                        <a
                            class="btn btn-outline-primary me-2"
                            href="{% url 'users:signin' %}"
                        >
                            Sign in
                        </a>
                    </form>
                    {% endif %}
                </div>
            </nav>

            {% if messages %}
            <div class="messages position-absolute">
                {% for message in messages %}

                <span
                    {%
                    if
                    message.tags
                    %}
                    class="alert alert-{{ message.tags }}"
                    {%
                    else
                    %}
                    class="alert alert-danger"
                    {%
                    endif
                    %}
                    >{{ message }}</span
                >
                {% endfor %}
            </div>
            {% endif %} {% block content%} {% endblock %}
        </div>
    </body>
</html>

quotes/quotes_app/templates/quotes_app/index.html
{% extends 'quotes_app/base.html' %} {% load extract %} {% block content %}

<!-- prettier-ignore  -->

<div class="add-author-wrapper mb-4 d-flex gap-2 justify-content-between">
    <a class="btn btn-primary justify-self-end" href="{% url 'quotes_app:top_tags' %}"
        >Top ten tags</a
    >

    {% if user.is_authenticated %}
    <div>
        <a class="btn btn-primary" href="{% url 'quotes_app:author_add' %}"
            >Add New Author</a
        >
        <a class="btn btn-primary" href="{% url 'quotes_app:quote_add' %}"
            >Add New Quote</a
        >
    </div>
    {% endif %}
</div>

<div class="quotes-wrapper mb-4 d-flex gap-4 flex-column">
    {% for quote in quotes %}

    <div class="card shadow" style="width: 100%">
        <div class="card-body">
            <p class="card-text">{{quote.quote}}</p>
            <div class="card-subtitle mb-4 text-body-secondary fw-semibold">
                <span>by</span>
                <span class="fst-italic">{{quote.author|author}}</span>
                <a
                    href="{% url 'quotes_app:author_info' author_id=quote.author.id %}"
                    >(about)</a
                >
            </div>

            <div class="tags-wrapper mb-4 d-flex gap-2">
                {% for tag in quote.tags %}
                <a
                    href="{% url 'quotes_app:quote_by_tag' tag_id=tag.id %}"
                    class="btn btn-outline-primary btn-sm"
                    >{{tag|tag_name}}</a
                >
                {% endfor %}
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li
            class="page-item {% if not quotes.has_previous %} disabled {% endif %}"
        >
            <a
                class="page-link"
                href="{% if quotes.has_previous %} {% url 'quotes_app:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"
                >Previous</a
            >
        </li>

        <li class="page-item">
            <a
                class="page-link {% if not quotes.has_next %} disabled {% endif %}"
                href="{% if quotes.has_next %} {% url 'quotes_app:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}"
                >Next</a
            >
        </li>
    </ul>
</nav>

{% endblock %}

quotes/quotes_app/templates/quotes_app/quote_add.html
{% extends 'quotes_app/base.html' %} {% block content %}
<div class="container mt-3 position-relative">
    <h2 class="mb-5">Add Quote</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label add-author-form"
                >Quote {{ form.quote }}
            </label>
            <div class="error-container">{{form.errors.quote}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label add-author-form"
                >Author {{ form.author }}
            </label>
            <div class="error-container">{{form.errors.author}}</div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>
    </form>
</div>
{% endblock %}

quotes/quotes_app/templates/quotes_app/quotes_tag.html
{% extends 'quotes_app/base.html' %} {% load extract %} {% block content %}

<h2 class="mb-5">
    Quotes with tag:
    <span class="btn btn-primary">{{ tag.name }}</span>
</h2>
<div class="quotes-wrapper mb-4 d-flex gap-4 flex-column">
    {% for quote in quotes %}
    <div class="card shadow" style="width: 100%">
        <div class="card-body">
            <p class="card-text">{{quote.quote}}</p>
            <div class="card-subtitle text-body-secondary fw-semibold">
                <span>by</span>
                <span class="fst-italic">{{quote.author|author}}</span>
                <a
                    href="{% url 'quotes_app:author_info' author_id=quote.author.id %}"
                    >(about)</a
                >
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

quotes/quotes_app/templates/quotes_app/top-tags.html
{% extends 'quotes_app/base.html' %} {% load extract %} {% block content %}
<h2 class="mb-5">
    <p>Top 10 tags:</p>

    {% for tag in top_tags %}
    <a
        href="{% url 'quotes_app:quote_by_tag' tag_id=tag.id %}"
        class="btn btn-primary"
        >{{tag|tag_name}}</a
    >
    {% endfor %}
</h2>

{% endblock %}