quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes_app.urls")),
    path("users/", include("users.urls")),
]

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views
from .forms import SigninForm

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path(
        "signin/",
        views.signinuser,
        name="signin",
    ),
    path(
        "signout/",
        LogoutView.as_view(template_name="users/signout.html"),
        name="signout",
    ),
    path("reset-password/", views.ResetPasswordView.as_view(), name="reset-password"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="reset-password-done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput


class SignupForm(UserCreationForm):
    username = CharField(
        max_length=20,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    email = EmailField(
        max_length=20, required=True, widget=EmailInput(attrs={"class": "form-control"})
    )
    password1 = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )
    password2 = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class SigninForm(AuthenticationForm):
    username = CharField(
        max_length=16,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    password = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ("username", "password")

quotes/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import SignupForm, SigninForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes_app:root")

    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes_app:root")
        else:
            return render(request, "users/signup.html", context={"form": form})

    return render(request, "users/signup.html", context={"form": SignupForm()})


def signinuser(request):
    if request.user.is_authenticated:
        return redirect("root")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        signin(request, user)
        return redirect(to="quotes_app:root")

    return render(request, "users/signin.html", context={"form": SigninForm()})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:reset-password-done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"

quotes/users/templates/users/password_reset.html
{% extends "quotes_app/base.html" %} {% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-primary">
        Request password reset
    </button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "quotes_app/base.html" %} {% block content %}

<h2>Password reset complete!</h2>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "quotes_app/base.html" %} {% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "quotes_app/base.html" %} {% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
    <p>Hi {{ user.username }},</p>
    <p>
        You requested a password reset for your account. Please follow this link
        to set a new password:
    </p>
    <p>
        <a
            href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}"
        >
            {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm'
            uidb64=uid token=token %}
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thanks,</p>
    <p>The Our Team</p>
    {% endautoescape %}
</body>

quotes/users/templates/users/signin.html
{% extends 'quotes_app/base.html' %} {% block content %}
<div class="container mt-3 position-relative">
    <h2 class="mb-5">Sign In</h2>

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
    {% endif %}

    <form action="{% url 'users:signin' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username {{ form.username }} </label>
            <div class="error-container">{{form.errors.username}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label">Password {{ form.password }} </label>
            <div class="error-container">{{form.errors.password}}</div>
        </div>
        <button type="submit" class="btn btn-primary">Confirm</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>

        <div class="btn btn-secondary">
            <a href="{% url 'users:reset-password' %}" class="text-center"
                ><i>Forgot Password?</i></a
            >
        </div>
    </form>
</div>
{% endblock %}

quotes/users/templates/users/signout.html
{% extends 'quotes_app/base.html' %} {% block content %}

<div class="container mt-3">
    <h2>
        See You soon!
        <span class="fw-bold fst-italic fs-4">{{user.username}}</span>
    </h2>
</div>

<script>
    window.setTimeout(function () {
        window.location.href = "/";
    }, 2000);
</script>

{% endblock %}

quotes/users/templates/users/signup.html
{% extends 'quotes_app/base.html' %} {% block content %}
<div class="container mt-3">
    <h2 class="mb-5">Sign Up</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username {{ form.username }} </label>
            <div class="error-container">{{form.errors.username}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label">Email {{ form.email }} </label>
            <div class="error-container">{{form.errors.email}}</div>
        </div>

        <div class="mb-3">
            <label class="form-label">Password {{ form.password1 }} </label>
            <div class="error-container">{{form.errors.password1}}</div>
        </div>
        <div class="mb-3">
            <label class="form-label"
                >Repeat Password {{ form.password2 }}
            </label>
            <div class="error-container">{{form.errors.password2}}</div>
        </div>
        <button type="submit" class="btn btn-primary">Confirm</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>
    </form>
</div>
{% endblock %}